name: isar_tasks_api
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  isar: 3.0.0-dev.8
  isar_flutter_libs: 3.0.0-dev.8
  tasks_api:
    path: ../tasks_api

dev_dependencies:
  build_runner: any
  flutter_test:
    sdk: flutter
  isar_generator: 3.0.0-dev.8
  very_good_analysis: ^3.0.1
