name: supabase_activities_api
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  activities_api:
    path: ../activities_api
  flutter:
    sdk: flutter
  intl: ^0.17.0
  rxdart: ^0.27.4
  supabase_flutter: ^0.3.1+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^2.4.0